name: Go CI

on:
  push:
    branches: [ "main", "develop" ]
  pull_request:
    branches: [ "main", "develop" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout código
      uses: actions/checkout@v4

    - name: Configurar Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.22'

    - name: Instalar dependencias
      run: go mod tidy

    - name: Compilar
      run: go build ./...

    - name: Ejecutar pruebas
      run: go test ./... -v
